package sql

import (
	"context"
	"fmt"
	"strings"

	"github.com/apito-io/engine/models"
	"github.com/apito-io/engine/utility"
	"github.com/uptrace/bun"
)

// relationSQLiteFKReferencedParentLogicalModels lists schema model names that appear as FK parents
// in REFERENCES `<physical_table>`(id) clauses generated by AddRelationFields (SQLite-compatible).
func relationSQLiteFKReferencedParentLogicalModels(from, to *models.ConnectionType) []string {
	if from == nil || to == nil {
		return nil
	}
	fr, tr := strings.TrimSpace(from.Relation), strings.TrimSpace(to.Relation)
	switch fr {
	case "has_one":
		switch tr {
		case "has_one":
			return []string{
				strings.TrimSpace(from.Model),
				strings.TrimSpace(to.Model),
			}
		case "has_many":
			// FK on child refers to parent's id (REFERENCES peer from.Model).
			return []string{strings.TrimSpace(from.Model)}
		default:
			return nil
		}
	case "has_many":
		switch tr {
		case "has_many":
			return []string{
				strings.TrimSpace(from.Model),
				strings.TrimSpace(to.Model),
			}
		case "has_one":
			return []string{strings.TrimSpace(to.Model)}
		default:
			return nil
		}
	default:
		return nil
	}
}

func sqlitePhysicalTableHasPrimaryKeyColumnID(ctx context.Context, db bun.IDB, physicalTable string) (bool, error) {
	pt := strings.TrimSpace(physicalTable)
	if pt == "" {
		return false, fmt.Errorf("empty physical table")
	}

	var cols []pragmaTableCol
	if err := db.NewRaw(`PRAGMA table_info(?)`, pt).Scan(ctx, &cols); err != nil {
		return false, err
	}
	for _, c := range cols {
		if strings.EqualFold(strings.TrimSpace(c.Name), "id") && c.PK > 0 {
			return true, nil
		}
	}
	return false, nil
}

// PreflightSQLiteRelationParentTablesForAddRelation fails fast when SQLite would later report
// "foreign key mismatch" because referenced parent lacks PRIMARY KEY involvement for `id`.
func PreflightSQLiteRelationParentTablesForAddRelation(ctx context.Context, db bun.IDB, engine string, from, to *models.ConnectionType) error {
	if db == nil {
		return nil
	}
	if !engineIsSQLiteLike(strings.TrimSpace(engine)) {
		return nil
	}
	logicals := relationSQLiteFKReferencedParentLogicalModels(from, to)
	seenPhy := map[string]string{}
	for _, logical := range logicals {
		logical = strings.TrimSpace(logical)
		if logical == "" {
			continue
		}
		phy := utility.PhysicalSQLTableName(logical)
		if _, dup := seenPhy[phy]; dup {
			continue
		}
		seenPhy[phy] = logical
		ok, err := sqlitePhysicalTableHasPrimaryKeyColumnID(ctx, db, phy)
		if err != nil {
			return fmt.Errorf("preflight FK parent table %s: %w", logical, err)
		}
		if !ok {
			return fmt.Errorf(`parent model %s does not have a valid primary key on 'id'; cannot create FK relation`, logical)
		}
	}
	return nil
}
