package utility

import (
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/apito-io/engine/models"
)

// IsValidIdentifier normalizes a field label or raw identifier into display label + canonical snake_case id.
// Word boundaries follow the same rules as CanonicalizeModelName (camelCase, spaces, underscores, hyphens).
func IsValidIdentifier(raw string) (*models.ValidIdentifier, error) {
	label := strings.TrimSpace(raw)
	if label == "" {
		return nil, errors.New("field name is required")
	}

	work := regexp.MustCompile(`\(([^)]+)\)`).ReplaceAllString(label, " $1 ")
	segments, err := splitIntoWordSegments(work)
	if err != nil {
		return nil, err
	}
	if len(segments) == 0 {
		return nil, errors.New("invalid field name")
	}

	identifier := strings.Join(segments, "_")
	identifier = regexp.MustCompile(`_+`).ReplaceAllString(identifier, "_")
	identifier = strings.Trim(identifier, "_")

	if strings.HasPrefix(identifier, "_") {
		return nil, errors.New("field can not begin with _")
	}
	if ArrayContains([]string{"id", "_id"}, identifier) {
		return nil, fmt.Errorf("field %s is auto generated by the System. No Need to define It", identifier)
	} else if ArrayContains([]string{"status"}, identifier) {
		return nil, errors.New("status field is auto generated and reserved for document publishing status in the API. Choose other name instead")
	} else if strings.HasPrefix(identifier, "sys_") {
		return nil, errors.New("field Name Starts with SYS/Sys is protected. Please Use alternative names")
	}

	var re = regexp.MustCompile(`^\d`)
	if len(re.FindAllString(identifier, -1)) > 0 {
		return nil, errors.New("field name can not start with a number! use character instead")
	}

	return &models.ValidIdentifier{
		Label:      label,
		Identifier: identifier,
	}, nil
}
