package utility

import (
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/apito-io/engine/models"
)

func IsValidIdentifier(identifier string) (*models.ValidIdentifier, error) {
	label := strings.TrimSpace(identifier)

	// First, convert to lowercase
	identifier = strings.ToLower(label)

	// Extract content from parentheses and replace parentheses with underscores
	// This will convert "Weight (KG)" to "weight_kg"
	identifier = regexp.MustCompile(`\(([^)]+)\)`).ReplaceAllString(identifier, "_$1")

	// Replace spaces, hyphens, dots, and other common separators with single underscore
	identifier = regexp.MustCompile(`[\s\-\._]+`).ReplaceAllString(identifier, "_")

	// Remove any remaining non-alphanumeric characters except underscores
	identifier = regexp.MustCompile(`[^a-z0-9_]`).ReplaceAllString(identifier, "")

	// Clean up multiple consecutive underscores
	identifier = regexp.MustCompile(`_+`).ReplaceAllString(identifier, "_")

	// Remove leading and trailing underscores
	identifier = strings.Trim(identifier, "_")

	// check for valid field name. Restrict a few
	if strings.HasPrefix(identifier, "_") {
		return nil, errors.New("field can not begin with _")
	}
	if ArrayContains([]string{"id", "_id"}, identifier) {
		return nil, fmt.Errorf("field %s is auto generated by the System. No Need to define It", identifier)
	} else if ArrayContains([]string{"status"}, identifier) {
		return nil, errors.New("status field is auto generated and reserved for document publishing status in the API. Choose other name instead")
	} else if strings.HasPrefix(identifier, "sys_") {
		return nil, errors.New("field Name Starts with SYS/Sys is protected. Please Use alternative names")
	}

	//check if model name starts with number
	var re = regexp.MustCompile(`^\d`)
	matchFound := re.FindAllString(identifier, -1)
	if len(matchFound) > 0 {
		return nil, errors.New("field name can not start with a number! use character instead")
	}
	return &models.ValidIdentifier{
		Label:      label,
		Identifier: identifier,
	}, nil
}
