name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.3

      - name: Install dependencies
        run: go mod tidy

      - name: Build static binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o hello-world-echo -ldflags "-w -s"

      - name: Zip binary
        run: zip hello-world-echo-${{ github.ref_name }}.zip hello-world-echo

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: hello-world-echo-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "This is an automatic release for version ${{ github.ref_name }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
